<a href="https://colab.research.google.com/github/DeanPhillipsOKC/numpy-notes/blob/master/NumPy_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy Iperations

In [0]:
import numpy as np

## Arrays and scalar math

When doing math where one operand is a numpy array, and the other is a scalar, the operation is performend on an element by element basis.

In [0]:
arr = np.arange(0, 11)

In [0]:
arr + 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [0]:
arr - 3

array([-3, -2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [0]:
arr * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [0]:
arr / 2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

## Array on array mathematical operations

When doing math where both operands are arrays, the math is done on an element by element basis (just like with scalar)

NOTE: To do array on array math, both must be the same shape

In [0]:
arr = np.arange(0, 11)

In [0]:
arr2 = np.arange(10, 21)

In [0]:
arr3 = np.arange(0, 5) # Not the same shape as the others

In [0]:
arr + arr2

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [0]:
arr2 - arr

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

In [0]:
arr + arr3

ValueError: ignored

In [0]:
arr * arr3

ValueError: ignored

In [0]:
arr * arr2

array([  0,  11,  24,  39,  56,  75,  96, 119, 144, 171, 200])

In [0]:
arr / arr2

array([0.        , 0.09090909, 0.16666667, 0.23076923, 0.28571429,
       0.33333333, 0.375     , 0.41176471, 0.44444444, 0.47368421,
       0.5       ])

NumPy handles division by zero for array division by setting the offending element to inf (if the numerator is also zero then it will be NaN), and displaying a runtime warning (not error)

In [0]:
arr2 / arr # First element will be inf because denominator is zero, and numerator is not

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([        inf, 11.        ,  6.        ,  4.33333333,  3.5       ,
        3.        ,  2.66666667,  2.42857143,  2.25      ,  2.11111111,
        2.        ])

In [0]:
arr / arr # First element will be nan, because both the denominator, and numerator are zero

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

## Other Mathematical Functions

This is just a few examples of other kinds of mathematical functions (e.g., square root, trigonometric,etc...)

Note: Behavior for array elements that would be undefined for that operation behave similarly to divison by zero (i.e. runtime warning is shown, and result is inf, or nan)

In [0]:
arr = np.arange(-5, 6)

In [0]:
np.sqrt(arr)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([       nan,        nan,        nan,        nan,        nan,
       0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798])

In [0]:
np.square(arr)

array([25, 16,  9,  4,  1,  0,  1,  4,  9, 16, 25])

In [0]:
np.sin(arr)

array([ 0.95892427,  0.7568025 , -0.14112001, -0.90929743, -0.84147098,
        0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427])

In [0]:
np.log(arr)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in log
  """Entry point for launching an IPython kernel.


array([       nan,        nan,        nan,        nan,        nan,
             -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791])

## Array Summary Statistics

In [0]:
arr = np.arange(-5, 6)

In [0]:
arr.sum()

0

In [0]:
arr.mean()

0.0

In [0]:
arr.min()

-5

In [0]:
arr.max()

5

In [0]:
arr.var() # Statistical variance

10.0

In [0]:
arr.std() # Standard deviation

3.1622776601683795

## Summary Statistics for Multidimensional Arrays

In [0]:
arr2d = np.arange(0, 25).reshape(5, 5)

In [0]:
arr2d.shape

(5, 5)

In [0]:
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

Sum all elements in the entire array

In [0]:
arr2d.sum()

300

Sum the columns.  This is confusing, but axis refers to the position of the shape specifier (in this case arr2d(x, y) it represents x which is at position zero.  While the result is technically all of the columns being summed, we are basically asking numpy to perform the sum across the rows

In [0]:
arr2d.sum(axis=0)

array([50, 55, 60, 65, 70])

Sum the rows. This is confusing, but axis refers to the position of the shape specifier (in this case arr2d(x, y) it represents y which is at position zero. While the result is technically all of the rows being summed, we are basically asking numpy to perform the sum across the columns

In [0]:
arr2d.sum(axis=1)

array([ 10,  35,  60,  85, 110])