<a href="https://colab.research.google.com/github/DeanPhillipsOKC/numpy-notes/blob/master/NumPy_Index_Selection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy Index Selection

In [0]:
import numpy as np

Create a 10 element array from 0 to 10

In [0]:
arr = np.arange(0, 11)

In [0]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Display the 3rd element of the array

In [0]:
arr[2]

2

Display the third element of the array, up to, but not including the 7th element

In [0]:
arr[3:7]

array([3, 4, 5, 6])

Both of these statements show elements 0, up to, but not including 5.  We can leave the 0 out, if we want to start at the beginning

In [0]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [0]:
arr[:5]

array([0, 1, 2, 3, 4])

Similar to above.  If we want our index range to go to the end, we can just leave off the end value

In [0]:
arr[5:11]

array([ 5,  6,  7,  8,  9, 10])

In [0]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

## Broadcasting

One thing numpy arrays do that normal Python arrays do not, is the ability to use broadcasts to assign to multiple elements.  In this example we select elements 2 to 4, and set them all to 100.

In [0]:
arr[2:5] = 100

In [0]:
arr

array([  0,   1, 100, 100, 100,   5,   6,   7,   8,   9,  10])

One thing that is important to know, is that when an array slice is taken, the new array is really just a pointer to a position in the original array.

This is shown in this example by taking a slice of our array, using a broadcast to change all elements of the slice, and showing that the corresponding elements in the original array were updates as well

In [0]:
arr = np.arange(0, 11) # Reset the array

In [0]:
slice_of_array = arr[0:6]

In [0]:
slice_of_array[:] = 100

In [0]:
slice_of_array

array([100, 100, 100, 100, 100, 100])

In [0]:
arr

array([100, 100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

If having a pointer to the original array is not adequate, we can use the built in copy method on the source array to get a completely new copy that can be updated independently.

In [0]:
arr = np.arange(0, 11) # Reset the array

In [0]:
copy_of_array = arr.copy()

In [0]:
copy_of_array[:] = 100

In [0]:
copy_of_array

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [0]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Indexing 2D Arrays

In [0]:
arr = np.arange(5, 46, 5)

In [0]:
arr = arr.reshape(3, 3)

Select the second and third row

In [0]:
arr[1:]

array([[20, 25, 30],
       [35, 40, 45]])

Select an individual element, the ugly way

In [0]:
arr[1][0]

20

Select an individual element the more common way

In [0]:
arr[1, 0]

20

Select the first, and second row, and second, and third column

In [0]:
arr[:2, 1:]

array([[10, 15],
       [25, 30]])

## Conditional Selection

Create an array from 0 to 10

In [0]:
arr = np.arange(0, 11)

Create a new 10 element array of booleans.  The elements in the original that are not greater than 4 will be false.  The others will be true.

In [0]:
elements_gt_4 = arr > 4

In [0]:
elements_gt_4

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

Use a broadcast to set all elements that are greater than 4 to 100

In [0]:
arr[elements_gt_4] = 100

In [0]:
arr

array([  0,   1,   2,   3,   4, 100, 100, 100, 100, 100, 100])

Here is a shorthand way of doing it

In [0]:
arr = np.arange(0, 11)

In [0]:
arr[arr > 4] = 200

In [0]:
arr

array([  0,   1,   2,   3,   4, 200, 200, 200, 200, 200, 200])