<a href="https://colab.research.google.com/github/DeanPhillipsOKC/numpy-notes/blob/master/Numpy_Arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

# Exercise 1: Transforming Python lists to NumPy arrays

Declare a 1d, and 2d array

In [0]:
array_1d = [1, 2, 3]

In [0]:
array_2d = [[1, 2], [3, 4], [5, 6]]

Print the arrays as normal python arrays

In [0]:
array_1d

[1, 2, 3]

In [0]:
array_2d

[[1, 2], [3, 4], [5, 6]]

Now print them as NumPy arrays (notice how the 2d one is shown as a 3x2 matrix)

In [0]:
np.array(array_1d)

array([1, 2, 3])

In [0]:
np.array(array_2d)

array([[1, 2],
       [3, 4],
       [5, 6]])

# Exercise 2: Generating Deterministic NumPy Arrays

## np.arrange

Create a 10 element array starting at 0


In [0]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Create a 5 element of even numbers starting at 0

In [0]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

## np.zeros

Create a five element array of floating point zeros

In [0]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

Create a 2x3 matrix of floating point zeros

In [0]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

Create a 4x5 matrix of integer zeros

In [0]:
np.zeros((4, 5), int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

## np.ones

Create a five element array of floating point ones

In [0]:
np.ones(5)

array([1., 1., 1., 1., 1.])

Create a 2x3 matrix of floating point ones

In [0]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

Create a 4x5 matrix of integer ones

In [0]:
np.ones((4, 5), int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [0]:
import numpy as np

## np.linspace (linear spaced)

This one is neat.  It will create a NumPy array that starts with the first parameter, ends with the second, and containst a total number of evenly spaced elements as indicated by the third parameter

Create an array of 3 (third parameter) evenly spaced elements starting at 0 (first parameter), and ending with 10 (second parameter)

In [0]:
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

Create an array of 20 (third parameter) evenly spaced elements starting with 0 (first parameter) and ending with 4 (second parameter)

In [0]:
np.linspace(0, 5, 20)

array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
       1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
       2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
       3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])

## np.eye (identity matrix)

Creates an identity matrix.  This matrix is square n x n matrix where n matches the parameter passed in.  Since it is an identity matrix, all elements will be zero, except for the diagonal.

In this example we will create a 5 x 5 (parameter) identity matrix

In [0]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# Exercise 3: Generating Random NumPy Arrays

## np.random.rand (random numbers with a uniform distribution)

Generate 3 random numbers between [0, 1) using a uniform distribution

In [0]:
np.random.rand(3)

array([0.75729869, 0.22318319, 0.51847582])

Generate a 2 x 3 matrix of random numbers between [0, 1) using a uniform distribution

In [0]:
np.random.rand(2, 3)

array([[0.65514582, 0.53250874, 0.40376752],
       [0.06317705, 0.0619053 , 0.84177003]])

## np.random.randn (random numbers with normal distribution

Generates 3 random numbers between (-1, 1) using a guassian distribution about a mean of zero, with a variance of 1

In [0]:
np.random.randn(3)

array([-0.77168272, -0.65444917, -1.4197402 ])

Generates a 2 x 3 matrix of random numbers between (-1, 1) using a guassian distribution about a mean of zero with a variance of 1

In [0]:
np.random.randn(2,3)

array([[-0.29733327, -1.27991299,  1.0483892 ],
       [ 1.99655717, -0.12234764,  0.0118505 ]])

## np.random.randint (random integer)

Generates a random integer between [1, 100)

In [0]:
np.random.randint(1, 100)

9

Generates 5 random integers between [1, 100)

In [0]:
np.random.randint(1, 100, 5)

array([91, 22, 98, 88, 67])

Generates a 2 x 3 matrix of random integers between [1, 100)

In [0]:
np.random.randint(1, 100, (2, 3))

array([[70,  1, 64],
       [93, 77, 52]])

## np.random.seed

This will seed the random number generator.  If a known value is passed in, then the random number generator will always generate the same random numbers.

In this example, anybody else that passes a 42 into the seed function will generate these same 4 random numbers.

In [0]:
np.random.seed(42)

In [0]:
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

# Exercise 4: Reshaping NumPy Arrays

Create a 25 element 1d array of integers starting with 0 and ending with 24 (n -1)

In [0]:
arr = np.arange(25)

Get the shape (currently a 25 element 1d array)

In [0]:
arr.shape

(25,)

Create a new array using the same data that is a 5 x 5

In [0]:
arr.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

Here we will get an error because a 3 x 6 array must contain 18 elements, but our source array contains 25.  So when using reshape the product of the parameters must equal the size of the array.

In [0]:
arr.reshape(3, 6)

ValueError: ignored

# Exercise 5: Array Info

Create an array of 10 random numbers between [1, 50)

In [0]:
randomArray = np.random.randint(1, 50, 10)

In [0]:
randomArray

array([39, 19, 23, 11, 11, 24, 36, 40, 24,  3])

Returns the max value from the array

In [0]:
randomArray.max()

40

Returns the index of hte max value from the array

In [0]:
randomArray.argmax()

7

Returns the min value from the array

In [0]:
randomArray.min()

3

Returns the index of the min value from the array

In [0]:
randomArray.argmin()

9

Get the datatype of the array elements

In [0]:
randomArray.dtype

dtype('int64')